import pytest

from PTT.handlers import add_defaults
from PTT.parse import Parser


@pytest.fixture
def parser():
    p = Parser()
    add_defaults(p)
    return p


@pytest.mark.parametrize('release_name, expected_languages, expected_subtitles', [
    ("Deadpool 2016 1080p BluRay DTS Rus Ukr 3xEng HDCL", ['ru-RU', 'uk-UA'], []),
    ("VAIANA: MOANA (2017) NL-Retail [2D] EAGLE", ['nl-NL'], []),
    ("De Noodcentrale S02E05 FLEMISH 540p WEBRip AAC H 264", ['nl-NL'], []),
    ("The Intern 2015 TRUEFRENCH 720p BluRay x264-PiNKPANTERS", ['fr-FR'], []),
    ("After Earth 2013 VFF BDrip x264 YJ", ['fr-FR'], []),
    ("127.Heures.FRENCH.DVDRip.AC3.XViD-DVDFR", ['fr-FR'], []),
    ("Color.Of.Night.Unrated.DC.VostFR.BRrip.x264", [], ['fr-FR']),
    ("Le Labyrinthe 2014 Multi-VF2 1080p BluRay x264-PopHD", ['multi', 'fr-FR'], []),
    ("Maman, j'ai raté l'avion 1990 VFI 1080p BluRay DTS x265-HTG", ['fr-FR'], []),
    ("South.Park.S21E10.iTALiAN.FiNAL.AHDTV.x264-NTROPiC", ['it-IT'], []),
    ("2- English- {SDH}.srt", [], ['en-US']),
    ("1_ English-Subs.srt", [], ['en-US']),
    ("House S 1 CD 1-6 svensk, danska, norsk, finsk sub", ['sv-SE', 'da-DK', 'no-NO'], ['fi-FI']),
    ("Svein.Og.Rotta.NORSK.Nordic.Subs.2006", ['no-NO'], ['da-DK', 'fi-FI', 'sv-SE', 'no-NO']),
    ("Borat med Norsk Undertekst", [], ['no-NO']),
    ("Subs/21_Bokmal.srt", [], ['no-NO']),
    ("Subs/nob.srt", [], ['no-NO']),
    ("Subs/5_nor.srt", [], ['no-NO']),
    ("Curious.George.2.Follow.That.Monkey.2009.DK.SWE.UK.PAL.DVDR-CATC", ['da-DK', 'sv-SE'], []),
    ("Yes.Man.Dk-Subs.2009.dingel", [], ['da-DK']),
    ("Dan-SDH.srt", [], ['da-DK']),
    ("dan.srt", [], ['da-DK']),
    ("Red Riding 1974 [2009 PAL DVD][En Subs[Sv.No.Fi]", ['en-US'], ['sv-SE', 'no-NO', 'fi-FI']),
    ("Comme une Image (Look at Me) [2004 PAL DVD][Fr Subs[Sv.Da.No]", ['fr-FR'], ['sv-SE', 'da-DK', 'no-NO']),
    ("A.Good.Day.To.Die.Hard.2013.SWESUB.DANSUB.FiNSUB.720p.WEB-DL.-Ro", [], ['sv-SE', 'da-DK', 'fi-FI']),
    ("The.Prisoner.1967-1968.Complete.Series.Subs.English+Nordic", [], ['en-US', 'da-DK', 'fi-FI', 'sv-SE', 'no-NO']),
    ("Royal.Pains.S05E02.HDTV.subtitulado.esp.sc.avi", ['es-ES'], []),
    ("Desmembrados (2006) [HDrip-XviD-AC3][Castellano]", ['es-ES'], []),
    ("10_Spanish-Subs.srt", [], ['es-ES']),
    ("Patriot Games [1992] Eng, Ger, Cze, Hun, Pol + multisub  DVDrip", ['en-US', 'de-DE', 'cs-CZ', 'hu-HU', 'pl-PL'], ['multi']),
    ("Elvis Presley - La via del Male (King creole) - IT EN FR DE ES", ['it-IT', 'en-US', 'fr-FR', 'de-DE', 'es-ES'], []),
    ("FernGully [H264 - Ita Dut Fre Ger Eng Spa Aac - MultiSub]", ['it-IT', 'nl-NL', 'fr-FR', 'de-DE', 'en-US', 'es-ES'], ['multi']),
    ("Jesus de Montreal / Jesus of Montreal - subtitulos espanol", ['es-ES'], []),
    ("Los.Vengadores.DVDR español ingles clon", ['es-ES', 'en-US'], []),
    ("EMPIRE STATE 2013 DVDRip TRNC English and Española Latin", ['en-US', 'es-ES', 'es-419'], []),
    ("Mary Poppins Returns 2019 DVDRip LATINO-1XBET", ['es-419'], []),
    ("Los Simpsons S18 E01 Latino", ['es-419'], []),
    ("Spider-Man (2002) Blu-Ray [720p] Dual Ingles-Español", ['en-US', 'es-ES'], []),
    ("Abuela (2015) 1080p BluRay x264 AC3 Dual Latino-Inglés", ['es-419', 'en-US'], []),
    ("Dumbo.2019.1080p.Dual.Lat", ['es-419'], []),
    ("A.Score.to.Settle.2019.lati.mp4", ['es-419'], []),
    ("[S0.E04] Gambit królowej - Gra środkowa.Spanish Latin America.srt", [], ['es-419']),
    ("Latin American.spa.srt", [], ['es-419']),
    ("Men in Black International 2019 (inglês português)", ['en-US', 'pt-BR'], []),
    ("Assassins (1995) Sylvester Stallone.DVDrip.XviD - Italian Englis", ['it-IT', 'en-US'], []),
    ("El Club de la Lucha[dvdrip][spanish]", ['es-ES'], []),
    ("The Curse Of The Weeping Woman 2019 BluRay 1080p Tel+Tam+hin+eng", ['te-IN', 'ta-IN', 'hi-IN', 'en-US'], []),
    ("Inception 2010 1080p BRRIP[dual-audio][eng-hindi]", ['en-US', 'hi-IN'], []),
    ("Inception (2010) 720p BDRip Tamil+Telugu+Hindi+Eng", ['ta-IN', 'te-IN', 'hi-IN', 'en-US'], []),
    ("Subs/Dear.S01E02.WEBRip.x265-ION265/34_tam.srt", [], ['ta-IN']),
    ("Subs/Dear.S01E02.WEBRip.x265-ION265/35_tel.srt", [], ['te-IN']),
    ("Dabangg 3 2019 AMZN WebRip Hindi 720p x264", ['hi-IN'], []),
    ("Quarantine [2008] [DVDRiP.XviD-M14CH0] [Lektor PL] [Arx]", ['pl-PL'], []),
    ("The Mandalorian S01E06 POLISH WEBRip x264-FLAME", ['pl-PL'], []),
    ("Carros 2 Dublado - Portugues BR (2011)", ['pt-BR'], []),
    ("A.Simple.Plan.1998.720p.BDRIP.X264.dublado.portugues.BR.gmenezes", ['pt-BR'], []),
    ("American.Horror.Story.S01E01.720p. PORTUGUÊS BR", ['pt-BR'], []),
    ("Angel.S05E19.legendado.br.rmvb", [], ['pt-BR']),
    ("Grimm S01E11 Dublado BR [ kickUploader ]", ['pt-BR'], []),
    ("InuYasha.EP161.ptBR.subtitles.[inuplace.com.br].avi", [], ['pt-BR']),
    ("Ghost.Rider.DivX_Gamonet(Ingles-Port.BR)-AC3.avi", ['en-US', 'pt-BR'], []),
    ("I Am David  legendado pt/br", [], ['pt-BR']),
    ("Lone Wolf and Cub 6 movies - legendas BR", [], ['pt-BR']),
    ("Wonder Woman Season 3 (H.264 1080p; English/Portuguese-BR)", ['en-US', 'pt-BR'], []),
    ("MIB 3 - Homens de Preto 2012 ( Audio EN-BR - Leg BR  Mkv 1280x69", ['en-BR'], ['pt-BR']),
    ("my wife is a gangster 3 legendado em PT(BR)", [], ['pt-BR']),
    ("A.Clockwork.Orange.1971.BRDRIP.1080p.DUAL.PORT-BR.ENG.gmenezes.m", ['pt-BR', 'en-US'], []),
    ("Superman I - O Filme 1978 Leg. BR - Mkv 1280x528", [], ['pt-BR']),
    ("Subs/Brazilian.por.srt", [], ['pt-BR']),
    ("Brazilian Portuguese.por.srt", [], ['pt-BR']),
    ("[S0.E07] Gambit królowej - Gra końcowa.Portuguese Brazil.srt", [], ['pt-BR']),
    ("The Hit List (2011) DVD NTSC WS (eng-fre-pt-spa) [Sk]", ['en-US', 'fr-FR', 'pt-BR', 'es-ES'], []),
    ("[POPAS] Neon Genesis Evangelion: The End of Evangelion [jp_PT-pt", ['ja-JP', 'pt-PT'], []),
    ("Zola Maseko - Drum (2004) PT subs", [], ['pt-BR']),
    ("Idrissa Ouedraogo - Yaaba (1989) EN ES FR PT", ['en-US', 'es-ES', 'fr-FR', 'pt-BR'], []),
    ("Metallica.Through.The.Never.2013 O Filme(leg.pt-pt)", [], ['pt-PT']),
    ("Dinossauro (2000) --[ Ing / Pt / Esp ]", ['en-US', 'pt-BR', 'es-ES'], []),
    ("The Guard 2011.DK.EN.ES.HR.NL.PT.RO.Subtitles", ['da-DK', 'en-US', 'es-ES', 'hr-HR', 'nl-NL', 'pt-BR'], ['ro-RO']),
    ("Titan.A.E.2000 720p  HDTV DTS Eng Fra Hun Rom Rus multisub", ['en-US', 'fr-FR', 'hu-HU', 'ro-RO', 'ru-RU'], ['multi']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Latin American es.ass", [], ['es-419']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Brazilian pt.ass", [], ['pt-BR']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.pt.ass", [], ['pt-BR']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.es.ass", [], ['es-ES']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.de.ass", [], ['de-DE']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.it.ass", [], ['it-IT']),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.ar.ass", [], ['ar-EG']),
    ("Subs(ara,fre,ger).srt", [], ['ar-EG', 'fr-FR', 'de-DE']),
    ("Subs(chi,eng,ind,kor,may,tha,vie).srt", [], ['zh-CN', 'en-US', 'id-ID', 'ko-KR', 'ms-MY', 'th-TH', 'vi-VN']),
    ("Miami.Bici.2020.1080p.NETFLIX.WEB-DL.DDP5.1.H.264.EN-ROSub-ExtremlymTorrents", ['en-US'], ['ro-RO']),
    ("26_Romanian.srt", [], ['ro-RO']),
    ("4_Bulgarian.srt", [], ['bg-BG']),
    ("18_srp.srt", [], ['sr-RS']),
    ("Aranyelet.S01.HUNGARIAN.1080p.WEBRip.DDP5.1.x264-SbR[rartv]", ['hu-HU'], []),
    ("Ponyo[2008]DvDrip-H264 Quad Audio[Eng Jap Fre Spa]AC3 5.1[DXO]", ['en-US', 'ja-JP', 'fr-FR', 'es-ES'], []),
    ("The Mechanic [1972] Eng,Deu,Fra,Esp,Rus + multisub DVDrip", ['en-US', 'de-DE', 'fr-FR', 'es-ES', 'ru-RU'], ['multi']),
    ("Mommie Dearest [1981 PAL DVD][En.De.Fr.It.Es Multisubs[18]", ['en-US', 'de-DE', 'fr-FR', 'es-ES'], ['multi']), # TODO: does not include it
    ("Pasienio sargyba S01E03 (2016 WEBRip LT)", ['lt-LT'], []),
    ("24_Lithuanian.srt", [], ['lt-LT']),
    ("25_Latvian.srt", [], ['lv-LV']),
    ("13_Estonian.srt", [], ['et-EE']),
    ("Ip.Man.4.The.Finale.2019.CHINESE.1080p.BluRay.x264.TrueHD.7.1.Atmos-HDC", ['zh-CN'], []),
    ("should parse CHT language", ['zh-Hant-TW'], []),
    ("Inuyasha_TV+Finale+OVA+Film+CD+Manga+Other; dub jpn,chn,eng sub chs (2019-09-21)", ['ja-JP', 'zh-CN', 'en-US'], ['zh-Hans-CN']),
    ("Initial D Live Action 2005 ENG/CHI", ['en-US', 'zh-CN'], []),
    ("Wolf.Warrior.2015.720p.BluRay.x264.Mandarin.AAC-ETRG", ['zh-CN'], []),
    ("Traditional Chinese.chi.srt", [], ['zh-Hant-TW']),
    ("Subs/Promare - Chinese (Traditional).ass", [], ['zh-Hant-TW']),
    ("Berserk 01-25 [dual audio JP,EN] MKV", ['ja-JP', 'en-US'], []),
    ("FLCL S05.1080p HMAX WEB-DL DD2.0 H 264-VARYG (FLCL: Shoegaze Dual-Audio Multi-Subs)", [], ['multi']),
    ("Shinjuku Swan 2015 JAP 1080p BluRay x264 DTS-JYK", ['ja-JP'], []),
    ("Wet.Woman.in.the.Wind.2016.JAPANESE.1080p.BluRay.x264-iKiW", ['ja-JP'], []),
    ("All.Love.E146.KOR.HDTV.XViD-DeBTV", ['ko-KR'], []),
    ("The.Nun.2018.KORSUB.HDRip.XviD.MP3-STUTTERSHIT", [], ['ko-KR']),
    ("Burning.2018.KOREAN.720p.BluRay.H264.AAC-VXT", ['ko-KR'], []),
    ("Atonement.2017.KOREAN.ENSUBBED.1080p.WEBRip.x264-VXTT", ['ko-KR'], ['en-US']),
    ("A Freira (2018) Dublado HD-TS 720p", ['pt-BR'], []),
    ("Escobar El Patron Del Mal Capitulo 91 SD (2012-10-10) [SiRaDuDe]", ['pt-BR'], []),
    ("Bleach - 215 ao 220 - [DB-BR]", ['pt-BR'], []),
    ("Joker.2019.MULTi.Bluray.1080p.Atmos.7.1.En.Fr.Sp.Pt-DDR[EtHD]", ['multi', 'en-US', 'fr-FR', 'es-ES', 'pt-BR'], []), # TODO: does not include sp,pt
    ("Dilbert complete series + en subs", [], ['en-US']),
    ("The Next Karate Kid (1994) NTSC WS -Eng/Fre/Spa/Por- [ctang]", ['en-US', 'fr-FR', 'es-ES', 'pt-BR'], []),
    ("arsenico por compasion 1944 Capra spanish castellano", ['pt-BR', 'es-ES'], []),
    ("Un.Homme.Et.Une.Femme.1966.DVDRip.XviD.AR [PT ENG ESP]", ['pt-BR', 'en-US', 'es-ES'], []),
    ("Geminis.2005.Argentina.ESP.ENG.PT.SUBS", ['es-ES', 'en-US'], ['pt-BR']),
    ("1917 2019 1080p Bluray x264-Sexmeup [Greek Subs] [Braveheart]", [], ['el-GR']),
    ("The Lion King 1,2,3 Greek Language", ['el-GR'], []),
    ("The Adams Family (1991) (Greek Subs integratet)", [], ['el-GR']),
    ("6_Greek.srt", [], ['el-GR']),
    ("The Insult (2017) [BluRay] [720p] Arabic", ['ar-EG'], []),
    ("The.Mexican.2001 - Arabic Subs Hardcoded", [], ['ar-EG']),
    ("Much Loved (2015) - DVDRip x265 HEVC - ARAB-ITA-FRE AUDIO (ENG S", ['ar-EG', 'it-IT', 'fr-FR', 'en-US'], []),
    ("42.2013.720p.BluRay.x264.HD4Ar Arab subtitle", [], ['ar-EG']),
    ("Fauda.S01.HEBREW.1080p.NF.WEBRip.DD5.1.x264-TrollHD[rartv]", ['he-IL'], []),
    ("madagascar 720p hebrew dubbed.mkv", ['he-IL'], []),
    ("Into.the.Night.S01E04.Ayaz.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track17_[heb].srt", [], ['he-IL']),
    ("The.Protector.2018.S03.TURKISH.WEBRip.x264-ION10", ['tr-TR'], []),
    ("Recep Ivedik 6 (2020) NETFLIX 720p WEBDL (Turkish) - ExtremlymTorrents", ['tr-TR'], []),
    ("The Insider*1999*[DVD5][PAL][ENG, POL, sub. ROM, TUR]", ['en-US'], ['pl-PL', 'ro-RO', 'tr-TR']),
    ("Divorzio allitaliana [XviD - Ita Mp3 - Sub Eng Esp Tur]", ['it-IT'], ['en-US', 'es-ES', 'tr-TR']),
    ("2007 Saturno Contro [Saturn In Opposition] (ITA-FRA-TUR) [EngSub", ['it-IT', 'fr-FR', 'tr-TR'], ['en-US']),
    ("Cowboy Bebop - 1080p BDrip Audio+sub MULTI (VF / VOSTFR)", ['fr-FR'], ['multi', 'fr-FR']),
    ("Casablanca 1942 BDRip 1080p [multi language,multi subs].mkv", ['multi'], ['multi']),
    ("Avengers.Endgame.2019.4K.UHD.ITUNES.DL.H265.Dolby.ATMOS.MSUBS-Deflate.Telly", [], []),
    ("Dawn of the Planet of the Apes (2014) 720p BluRay x264 - MULTI S", ['multi'], []),
    ("Pirates of the Caribbean On Stranger Tides (2011) DVD5 (Multi Su", ['multi'], []),
    ("Jumanji The Next Level (2019) 720p HDCAM Ads Blurred x264 Dual A", [], []),
    ("Men in Black International (2019) 720p Korsub HDRip x264 ESub [Dual Line Audio] [Hindi English]", ['hi-IN', 'en-US'], ['ko-KR', 'en-US']),
    ("Fame (1980) [DVDRip][Dual][Ac3][Eng-Spa]", ['en-US', 'es-ES'], []),
    ("O Rei do Show 2018 Dual Áudio 4K UtraHD By.Luan.Harper.", [], []),
    ("Cowboy Bebop The Movie (2001) BD 1080p.x265.Tri-Audio.Ita.Eng.Jap [Rady]", ['it-IT', 'en-US', 'ja-JP'], []),
    ("[IceBlue] Naruto (Season 01) - [Multi-Dub][Multi-Sub][HEVC 10Bits] 800p BD", ['multi'], ['multi']),
    ("Blue Seed - 01 (BDRip 720x480p x265 HEVC FLAC, AC3x2 2.0x3)(Triple Audio)[sxales].mkv", [], []),
    ("Ministri S01E02 SLOVAK 480p x264-mSD", ['sk-SK'], []),
    ("Subs/35_slo.srt", [], ['sk-SK']),
    ("Seinfeld.COMPLETE.SLOSUBS.DVDRip.XviD", [], ['sk-SK']),
    ("Subs/36_Slovenian.srt", [], ['sl-SI']),
    ("The House Bunny (2008) BDRemux 1080p MediaClub [RUS, UKR, ENG]", ['ru-RU', 'uk-UA', 'en-US'], []),
    ("L'immortel (2010) DVDRip AVC (Russian,Ukrainian)", ['ru-RU', 'uk-UA'], []),
    ("Into.the.Night.S01E03.Mathieu.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track33_[vie].srt", [], ['vi-VN']),
    ("Subs/vie.srt", [], ['vi-VN']),
    ("Subs/Vietnamese.vie.srt", [], ['vi-VN']),
    ("Subs/Dear.S01E05.WEBRip.x265-ION265/25_may.srt", [], ['ms-MY']),
    ("Midnight.Diner.Tokyo.Stories.S02E10.WEBRip.x264-ION10/14_Indonesian.srt", [], ['id-ID']),
    ("Inglês,Português,Italiano,Francês,Polonês,Russo,Norueguês,Dinamarquês,Alemão,Espanhol,Chinês,Japonês,Coreano,Persa,Hebraico,Sueco,Árabe,Holandês,Tâmil,Tailandês", ['en-US', 'pt-BR', 'it-IT', 'fr-FR', 'pl-PL', 'ru-RU', 'no-NO', 'da-DK', 'de-DE', 'es-ES', 'zh-CN', 'ja-JP', 'ko-KR', 'fa-IR', 'he-IL', 'sv-SE', 'ar-EG', 'nl-NL', 'ta-IN', 'th-TH'], []),
    ("russian,english,ukrainian", ['ru-RU', 'en-US', 'uk-UA'], []),
    ("Subs/Thai.srt", [], ['th-TH']),
    ("Food Choices (2016) WEB.1080p.H264_tha.srt", [], ['th-TH']),
    ("Ekk Deewana Tha (2012) DVDRip 720p x264 AAC TaRa.mkv", [], []),
    ("My Big Fat Greek Wedding (2002) 720p BrRip x264 - YIFY", [], []),
    ("Get Him to the Greek 2010 720p BluRay", [], []),
    ("[Hakata Ramen] Hoshiai No Sora (Stars Align) 01 [1080p][HEVC][x265][10bit][Dual-Subs] HR-DR", [], []),
    ("The English Patient (1996) 720p BrRip x264 - YIFY", [], []), # TODO: should have title "The English Patient"
    ("Do.Or.Die.1991.1080p.BluRay.x264-[YTS.LT].mp4", [], []),
    ("Castlevania 2017 1º temporada completa 1080p", ['es-ES'], []),
    ("City on a Hill - Temporada 1 [HDTV][Cap.110].avi", ['es-ES'], []),
    ("La inocencia [720p][wWw.EliteTorrent.NL].mkv", ['es-ES'], []),
    ("Reasonable Doubt - Temporada 1 [HDTV][Cap.101][www.AtomoHD.FI]", ['es-ES'], []),
    ("1883 - Temporada 1 [HDTV 720p][Cap.103][AC3 5.1][www.AtomoHD.fi]", ['es-ES'], []),
    ("Los Winchester - Temporada 1 [HDTV][Cap.103][www.atomoHD.tw]", ['es-ES'], []),
    ("El Inmortal- Temporada 1 [HDTV 720p][Cap.104][AC3 5.1][www.AtomoHD.ch]]", ['es-ES'], []),
    ("Black Friday (2021) [BluRay Rip][AC3 5.1][www.atomixHQ.TEL]", [], []),
    ("Deep Blue Sea 3 [HDR][wWw.EliteTorrent.SE]", [], []),
    ("The.Italian.Job.1969.1080p.BluRay.x265-RARBG.mp4", [], []),
    ("Chinese Zodiac (2012) 1080p BrRip x264 - YIFY", [], []),
    ("The German Doctor 2013 1080p WEBRip", [], []),
    ("Johnny English 2003 1080p BluRay", [], []),
    ("Polish Wedding (1998) 1080p (moviesbyrizzo upl).mp4", [], []),
    ("Russian.Doll.S02E02.2160p.NF.WEB-DL.DDP5.1.HDR.DV.HEVC-PEXA.mkv", [], []),
    ("The.Spanish.Prisoner.1997.1080p.BluRay.x265-RARBG", [], []),
    ("Japanese.Story.2003.1080p.WEBRip.x264-RARBG", [], []),
    ("[ Torrent9.cz ] The.InBetween.S01E10.FiNAL.HDTV.XviD-EXTREME.avi", [], []),
    ("Thai Massage (2022) 720p PDVDRip x264 AAC.mkv", [], []),
    ("Carson Daly 2017 09 13 Dan Harmon 720p HDTV x264-CROOKS", [], []),
    ("Dan Browns The Lost Symbol S01E03 1080p WEB H264-GLHF", [], []),
    ("Ben.Ara.2015.1080p.WEBRip.x265-RARBG.mp4", [], []),
    ("Ara.(A.Break).2008.DVDRip", [], []),
    ("www.1TamilMV.cz - Mirzapur (2020) S02 EP (01-10) - HQ HDRip - [Tam+ Tel] - x264 - AAC - 1GB - ESub", ['ta-IN', 'te-IN'], ['en-US']),
    ("www.1TamilMV.cz - The Game of Chathurangam (2023) WEB-DL - 1080p - AVC - (AAC 2.0) [Tamil + Malayalam] - 1.2GB.mkv", ['ta-IN', 'ml-IN'], []),
    ("www.1TamilMV.yt - Anchakkallakokkan (2024) Malayalam HQ HDRip - 720p - HEVC - (DD+5.1 - 192Kbps & AAC) - 750MB - ESub.mkv", ['ml-IN'], ['en-US']),
    ("Anatomia De Grey - Temporada 19 [HDTV][Cap.1905][Castellano][www.AtomoHD.nu].avi", ['es-ES'], []),
    ("Godzilla.x.Kong.The.New.Empire.2024.2160p.BluRay.REMUX.DV.P7.HDR.ENG.LATINO.GER.ITA.FRE.HINDI.CHINESE.TrueHD.Atmos.7.1.H265-BEN.THE.MEN", ['en-US', 'es-419', 'de-DE', 'it-IT', 'fr-FR', 'hi-IN', 'zh-CN'], []),
    ("Sampurna.2023.Bengali.S02.1080p.AMZN.WEB-DL.DD+2.0.H.265-TheBiscuitMan", ['bn-BD'], []),
    ("Kingdom.of.the.Planet.of.the.Apes.2024.HDRIP.1080P.[xDark [SaveHD] Latin + English + Hindi.mp4", ['es-419', 'en-US', 'hi-IN'], []),
    ("The Karate Kid Part III 1989 1080p DUAL TİVİBU WEB-DL x264 AAC - HdT", ['tr-TR'], []),
    ("The French Connection 1971 Remastered BluRay 1080p REMUX AVC DTS-HD MA 5 1-LEGi0N", [], []),
    ("The.Gorge.2025.PLSUB.1080p.ATVP.WEB-DL.DDP5.1.Atmos.H.264-APEX.mkv", [], ['pl-PL']),
])
def test_languages_detection(release_name, expected_languages, expected_subtitles, parser):
    result = parser.parse(release_name)
    assert isinstance(result, dict)
    assert result.get("audio_languages") == expected_languages, f"Failed for {release_name}"
    assert result["subtitle_languages"] == expected_subtitles


@pytest.mark.parametrize('release_name, expected_languages, expected_subtitles', [
    ("madagascar 720p hebrew dubbed.mkv", ['Hebrew (Israel)'], []),
    ("Into.the.Night.S01E04.Ayaz.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track17_[heb].srt", [], ['Hebrew (Israel)']),
    ("The.Protector.2018.S03.TURKISH.WEBRip.x264-ION10", ['Turkish (Türkiye)'], []),
    ("Recep Ivedik 6 (2020) NETFLIX 720p WEBDL (Turkish) - ExtremlymTorrents", ['Turkish (Türkiye)'], []),
    ("The Insider*1999*[DVD5][PAL][ENG, POL, sub. ROM, TUR]", ['English (United States)'], ['Polish (Poland)', 'Romanian (Romania)', 'Turkish (Türkiye)']),
    ("Japanese.Story.2003.1080p.WEBRip.x264-RARBG", [], []),
    ("[ Torrent9.cz ] The.InBetween.S01E10.FiNAL.HDTV.XviD-EXTREME.avi", [], []),
    ("Thai Massage (2022) 720p PDVDRip x264 AAC.mkv", [], []),
])
def test_translate_languages(release_name, expected_languages, expected_subtitles, parser):
    result = parser.parse(release_name, translate_languages=True)
    assert result["audio_languages"] == expected_languages
    assert result["subtitle_languages"] == expected_subtitles
